name: CI Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --bind_ip_all
        env:
          MONGO_INITDB_DATABASE: streaming_selector
    env:
      MONGO_URI: mongodb://localhost:27017/streaming_selector
      # Add any additional environment variables needed for testing
      # For example:
      # REACT_APP_API_URL: http://localhost:5173/api

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies for both client and server
      - name: Install dependencies
        run: npm run install-all

      # Create the .env file for the server
      - name: Create .env file
        run: |
          cp server/.env.example server/.env
          echo "MONGO_URI=${{ env.MONGO_URI }}" >> server/.env

      # Seed MongoDB with your seed data
      - name: Seed MongoDB
        run: |
          mongoimport --db streaming_selector --collection movies --file data/streaming_selector.movies.json --jsonArray
          mongoimport --db streaming_selector --collection questions --file data/streaming_selector.questions.json --jsonArray

      # Run tests or dev setup
      - name: Run development setup
        run: npm run dev
